### ISSUE TITLE
THE deauth option is not working when i select an ap and start the deauth attack nothing happens at first i thought theres something wrong with the button so i made some changes in the html  but its still not working can you please the code of the deauther  and thanks for the evil twin one its working perfectly

### ISSUE THREAD

**Issue by jsjadh** [p3tr0s/PhiSiFi#15]

**Comment by p3tr0s** [comment]
https://github.com/p3tr0s/PhiSiFi/blob/main/README.md

https://blog.spacehuhn.com/wifi-deauthentication-frame

https://blog.spacehuhn.com/deauth-attack-not-working

**Comment by jsjadh** [comment]
> https://github.com/p3tr0s/PhiSiFi/blob/main/README.md
> 
> https://blog.spacehuhn.com/wifi-deauthentication-frame
> 
> https://blog.spacehuhn.com/deauth-attack-not-working

I know it works only in WPA2 in 802.11 standard and i am trying on WPA2 with 802 standard but it still not works but if i try any other repositories like the ZIFI one then it works so what is the problem
