### ISSUE TITLE
Must find the bin file 😆😆

### ISSUE THREAD

**Issue by Lerwbd** [p3tr0s/PhiSiFi#6]
How can I redo the "wifi" sign to make it more user-friendly?, seems like deauther doesn't work anymore!?...."I use google translate". Everything worked fine 🥹🥹

**Comment by p3tr0s** [comment]
I am sorry but I don't really understand.

**Comment by Lerwbd** [comment]
Làm sao để thay đổi "giao diện" khi Đăng nhập ??.... Bạn có thể dạy tôi Một cách chi tiết không ?. Một người dùng mới 😅😅

**Comment by Lerwbd** [comment]
How to change the "interface" when logging in??.... Can you teach me in detail?. A new user 😅😅

**Comment by reyxv16** [comment]
Hello, the deauther function is not working :-(
